config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length:{minimum:3, maximum: 30}
    validates :description, presence: true, length:{minimum:3, maximum: 240}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:edit, :update, :show, :destroy]

    def index
        @articles = Article.all
    end
    
    def new
        @article = Article.new
    end

    def create 
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article was saved successfully"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end



    def destroy
        @article.destroy
        flash[:notice] = "Article was destroyed"
        redirect_to articles_path
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated"
            redirect_to article_path(@article)
        else
            flash[:notice] = "Article was not updated"
            render 'edit'
        end
    end

    private
        def article_params
            params.require(:article).permit(:title, :description)
        end

        def set_article
           @article = Article.find(params[:id])
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end

    def about 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>Warning: these errors prevent you from editing the current article</h2>
<ul>
<%@article.error.full_messages.each do |msg | %>
<li><%= msg%></li>
<%end%>
</ul>
<% end %>

<%= form_for @article do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<%end%>

app/views/articles/edit.html.erb
<h1>edit article</h1>

<%= render 'form'%>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1> All articles</h1> <br>

<table>
<tr>
<th>Title</th>
<th>Description</th>
</tr>

<%@articles.each do |article| %>
<tr>
<td><h3><%= article.title%></h3></td>
<td><p><%= article.description%></p></td>
<td><%= link_to 'Edit', edit_article_path(article) %></td>
<td><%= link_to 'Show', article_path(article) %></td>
<td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
</tr>
<% end %>
</table>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= form_for @article do |f| %>
 <p>
  <%= f.label :title %>
  <%= f.text_field :title %>
 </p>
   <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
 </p>
  <p>
  <%= f.submit %>
 </p>

 <% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>

<% end %>

app/views/articles/show.html.erb
<h1>Showing selected article <%=@article.id%> </h1>
<p>
 Title: <%= @article.title %>
</p>
<p>
 Description: <%= @article.description %>
</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/navigation' %>
    <%= yield %>
   
  </body>

  <% flash.each do |name, msg| %>
    <ul>
     <p>Status: <%= msg %>!</p>
    </ul>
<% end %>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<h1>Welcome to the blog</h1>
<%= link_to 'About', about_path %>